<!DOCTYPE html>
<html>
<head>
<title>Entrada al sistema de anuncios</title>
<style>
form{width:50ex;margin:auto}
label{font-weight: bold}
 input{display: block;}
</style>
</head>
<body>

<form method="post">
	<?php View::content()?>
	<label>Usuario <input type="text" name="usuario"/></label>
	<label>Contraseña <input type="password" name="hash"/></label>
	<button type="submit">Entrar</button>
</form>
</body>
</html>